version: '3'
services:
  rtsp-server:
    image: bluenviron/mediamtx:1.3.1
    environment:
      MTX_PROTOCOLS: "tcp,udp"
    network_mode: "host"
    volumes:
      - "./mediamtx.yml:/mediamtx.yml"
      - "./mediamtx.log:/mediamtx.log"
    restart: always
