version: '3'
services:
  rtsp-server:
    image: bluenviron/mediamtx:1.3.1
    environment:
      MTX_PROTOCOLS: "tcp,udp"
    network_mode: "host"
    volumes:
      - "./mediamtx.yml:/mediamtx.yml"
      - type: bind
        source: ./mediamtx.log
        target: /mediamtx.log
    restart: always
